config/routes.rb
Rails.application.routes.draw do
  
  resources :blogs
  
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'faq', to: 'pages#faq'
  get 'discussion', to: 'pages#discussion'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully creted' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed' }
      format.json { head :no_content }
    end
  end


  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :author, :date, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def faq
  end

  def contact
  end

  def discussion
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  
  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%= f.text_field :author, class: 'form-control', placeholder: 'Author' %>
  </div>

  <div class="form-group">
    <%= f.date_field :date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, rows: 5, class: 'form-control', placeholder: 'Content...' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Save Blog', class: 'btn btn-outline-success btn-block' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="new-blog">
  <div class="row">
    <div class="col-sm-6">
      <div class="text-left">
        <h2>New Blog</h2>
      </div>
      <div class="form marg">
        <%= render 'form', blag: @blog %>
      </div>
      <div class="marg">
        <%= link_to 'Show', @blog, class: 'btn btn-sm' %> |
        <%= link_to 'Back', blogs_path, class: 'btn btn-sm' %> |
        <%= link_to 'Delete', @blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm' %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<div class='blog-container'>
  <h1>Blogs</h1>

  <div class="marg">
    <% @blogs.each do |blog| %>
      <div>
        <%= link_to blog.title, blog_path(blog) %>
      </div>
      <div>
        <%= blog.author %>
      </div>
      <div>
        <%= blog.body %>
      </div>
    <% end %>
  </div>

  <div class="marg">
    <%= link_to 'Make a new post', new_blog_path, class: 'btn btn-outline-primary' %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="new-blog">
  <div class="row">
    <div class="col-sm-6">
      <div class="text-left">
        <h2>New Blog</h2>
      </div>
      <div class="form marg">
        <%= render 'form', blag: @blog %>
      </div>
      <div class="marg">
        <%= link_to 'Back', blogs_path %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<h1 class="show-title"><%= @blog.title.upcase %></h1>


<div class="row">
  <div class="col-sm-8">
    <div>
      <%= @blog.author %>
      <%= @blog.date %>
    </div>
    <%= @blog.body %>
  </div>

</div>

<div class="generic-buttons">
  <%= link_to 'Edit', edit_blog_path, class: 'btn btn-sm' %> |
  <%= link_to 'Back', blogs_path, class: 'btn btn-sm' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">

          <%= render "shared/application_nav" %>

          <%= yield %>

        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Nah, I'd rather you not know about me.</h1>

app/views/pages/contact.html.erb
<h1>Where I'd tell you how to get in touch with me.</h1>

app/views/pages/discussion.html.erb
<h1>Discuss something</h1>

app/views/pages/faq.html.erb
<h1>FAQ's</h1>

app/views/pages/home.html.erb
<div class="inner cover">
  <h1 class="cover-heading">Welcome to my Site</h1>
  <p class="lead">This is my site! Any errors you may come across... Deal with it. I'm not sorry.</p>
  <p class="lead">
    <%= link_to "About Me", about_path, class: "btn btn-lg btn-secondary" %>
  </p>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Howdy</h3>
    <nav class="nav nav-masthead">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About Me", about_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "FAQ", faq_path, class: 'nav-link' %>
      <%= link_to "Discussion", discussion_path, class: 'nav-link' %>
      <%= link_to "Blogs", blogs_path, class: 'nav-link' %>
      
    </nav>
  </div>
</div>

app/views/shared/_nav.html.erb
<%= link_to"Home", root_path %>
<%= link_to"About", pages_about_path %>
<%= link_to"FAQ", pages_faq_path %>
<%= link_to"Contact", pages_contact_path %>
<%= link_to"Discussion", pages_discussion_path %>
<%= link_to"Blogs", blogs_path %>